#!/bin/sh

hyrax_ver=$1
olfs_ver=$2

# Tag For OLFS version
git tag -a olfs-$olfs_ver -m "OLFS $olfs_ver"
git push origin olfs-$olfs_ver

# Tag For Hyrax version
git tag -a hyrax-$hyrax_ver -m "Hyrax $hyrax_ver"
git push origin hyrax-$hyrax_ver