#!/bin/bash

bes_location=$1
bes_location=${bes_location:-../bes}

bes_version="bes-$(cd "$bes_location" && git branch | grep "\*" | awk '{print $2}' -)-$(cd "$bes_location" && git log | head -1 | awk '{print $2}' -)"
echo "bes_version: $bes_version"

olfs_version="olfs-$(git branch | grep "\*" | awk '{print $2}' -)-$(git log | head -1 | awk '{print $2}' -)"
echo "olfs_version: $olfs_version"

ant -DHYRAX_VERSION=$bes_version -DOLFS_VERSION=$olfs_version server




