#!/bin/sh

hyrax_version=1.13.1
olfs_version=1.16.0

lastUpdate=`head -1 ChangeLog | awk '{print $1;}' -`
now=`date "+%Y-%m-%d" `

echo "$now ---  hyrax=$hyrax_version olfs=$olfs_version  " > olfs-$olfs_version.changes
echo " " >> olfs-$olfs_version.changes
gitlog-to-changelog --since=$lastUpdate >> olfs-$olfs_version.changes
echo " " >> olfs-$olfs_version.changes
echo "$lastUpdate ---  hyrax=1.13.0 olfs=1.15.0  " >> olfs-$olfs_version.changes
echo " " >> olfs-$olfs_version.changes
cat olfs-$olfs_version.changes ChangeLog >> foo
mv foo ChangeLog



