#!/bin/bash
#
# Usage: testGrind [value for catalina_home] [processes] [num laps] [tests to run]

# Provide a way to set CATALINA_HOME when it's not set in the shell.
CATALINA_HOME="${CATALINA_HOME:-$1}"
if test -z "$CATALINA_HOME"
then
    echo "Specify tomcat location"
    exit 1
fi

PROCS=${2:-"9"}
echo "PROCS: $PROCS"

# num laps is the number of failing laps
num_laps=${3:-1}
echo "num laps: $num_laps"

TESTS=${4:-"3 13 14 15 17 24 25 26 35 36 37 43 44 45 53 54 55"}
echo "TESTS: $TESTS"

PATH=/Users/jimg/src/opendap/hyrax_git/build/bin:/Users/jimg/src/opendap/hyrax_git/build/deps/bin:$PATH
echo "which getdap4: `which getdap4`"

# olfs_log_dir="/etc/olfs/logs"
olfs_log_dir="$CATALINA_HOME/webapps/opendap/WEB-INF/conf/logs"

flush_list="${olfs_log_dir}/BESCommands.log ${olfs_log_dir}/HyraxAccess.log ${olfs_log_dir}/HyraxErrors.log $CATALINA_HOME/logs/catalina.out";

fail_count=0
lap_count=0
status=0
while [  $fail_count -lt $num_laps ]; do
    # echo "Flushing $flush_list";

    for flush_me in $flush_list
    do
        >  ${flush_me};
    done

    echo "./hyraxTest --jobs=$PROCS $TESTS > mk-$fail_count.log 2>&1"
    ./hyraxTest --jobs=$PROCS $TESTS > mk-$fail_count.log 2>&1
    status=$?

    echo "Test pass: $lap_count     status: $status"
    if [ $status -ne 0 ]
    then
        echo "FAIL DETECTED!!!"
        let fail_count=$fail_count+1
    fi

    let lap_count=lap_count+1
done
 
