#!/bin/bash

source_file=${1:-"ngap-504.html"}
target_file=${2:-"504.html"}
s3_bucket="s3://cloudfront-error-pages-67a481d4de3acf4cec92538c42a6895f/"
s3_dir="error-pages-67a481d4de3acf4cec92538c42a6895f/"

target_s3_obj_url="${s3_bucket}${s3_dir}${target_file}"

echo "Copying ${source_file} to ${target_s3_obj_url}" >&2
aws s3 cp "${source_file}" "${target_s3_obj_url}"





