#!/bin/bash

echo "TRAVIS_BUILD_NUMBER: ${TRAVIS_BUILD_NUMBER}"
source ./VERSION

export OLFS_BUILD_NUMBER=$(expr $TRAVIS_BUILD_NUMBER - $TRAVIS_OLFS_BUILD_OFFSET)
export OLFS_BUILD_TAG="olfs-${OLFS_VERSION}-${OLFS_BUILD_NUMBER}"
echo "OLFS_BUILD_TAG: ${OLFS_BUILD_TAG}"

export HYRAX_BUILD_NUMBER=$(expr $TRAVIS_BUILD_NUMBER - $TRAVIS_HYRAX_BUILD_OFFSET)
export HYRAX_BUILD_TAG="hyrax-${HYRAX_VERSION}-${HYRAX_BUILD_NUMBER}"
echo "HYRAX_BUILD_TAG: ${HYRAX_BUILD_TAG}"
