# Test the OLFS netcdf handling.
#
# $Id$


global comp_output		# contains output from das-test_start
global verbose			# this and srcdir are set by runtest.exp
global srcdir

# The `1' in compare_stdout means call xfail if the test fails.








curl_all "http://localhost:8080/opendap/data/nc/fnoc1.nc" "testsuite/nc/fnoc1.nc"
curl_all "http://localhost:8080/opendap/data/nc/fnoc1.nc" "testsuite/nc/fnoc1.nc.lat" "lat"

curl_all "http://localhost:8080/opendap/data/nc/bears.nc" "testsuite/nc/bears.nc"
curl_all "http://localhost:8080/opendap/data/nc/bears.nc" "testsuite/nc/bears.nc.bears,aloan,i" "bears,aloan,i"

